### ISSUE TITLE
Seriously, mamot.fr ?! 

### ISSUE THREAD

**Issue by shakasan** [sgrigson/oliphant#10]
Sorry, but I will be very straightforward, why  mamot.fr is in this block list?

Is it a joke?

This is the mastodon instance of La Quadrature Du Net which is the equivalent in France of organization such as EFF.

I can easily understand some instances should be blocked, but what the heck? You add instances on which criteria?

Mamot.fr should not be in this block list and thus should be removed asap.

**Comment by Exagone313** [comment]
There is even piaille.fr, a major French instance created recently by a company that often contributes to free software and associations around the topic.

**Comment by minirop** [comment]
it was sourced from rage.love https://github.com/sgrigson/oliphant/blob/main/blocklists/rage.love.csv#L577 (same for piaille.fr)
also visible [here](https://rage.love/about#unavailable-content)

**Comment by tyrosinase** [comment]
It's explained right here: https://writer.oliphant.social/oliphant/the-blocklist-algorithm

**Comment by 240-185** [comment]
> It's explained right here: https://writer.oliphant.social/oliphant/the-blocklist-algorithm

You would be interested in that thing called "manual review", instead of blindly trusting algorithms.

**Comment by u03c1** [comment]
> It's explained right here: https://writer.oliphant.social/oliphant/the-blocklist-algorithm

Hi,

Could you explain why you choose the "rage.love" blocklist as a source of truth, even for a tier 3 perspective ? The list is huge, seems kinda "random", and looking at https://rage.love/about#about-rage-love-en, the column "Reason" is empty for ALL the domains listed.

**Comment by Deuchnord** [comment]
I heard about this blocklist just yesterday, I feel it like a nightmare, and not only because I'm on Mamot.fr myself: the Fediverse is a decentralized network by design, and now we are building a giant centralized block list, based on an algorithm that would be fed by 9 servers [out of more than 12K](https://fediverse.party/en/mastodon/)!? Not to mention that one of those servers is literally this list maintainer's one.

I've read on #8 that some instances had been added to this list because they didn't block some problematic servers, but do you realize that they are not necessarily connected to them and, thus, don't need to block them until they get connected?

Honestly, to me this blocklist has no sense. You have the right to block any instance (even the historic ones) for whatever reason on your own server, but every instance admin should make the decision by themselves, not use such list that makes them block literally 14% of the Mastodon federation without even knowing why.

**Comment by tyrosinase** [comment]
> Could you explain why you choose the "rage.love" blocklist as a source of truth, even for a tier 3 perspective ? The list is huge, seems kinda "random", and looking at https://rage.love/about#about-rage-love-en, the column "Reason" is empty for ALL the domains listed.

It's handy to have just because if I do have an issue with a site on this list, I know I can ask rage.love and see if it's an ongoing pattern or a one-off. That's kind of what a tier 3 perspective *is*, at least to me (I can't speak for oliphant).

**Comment by tyrosinase** [comment]
> every instance admin should make the decision by themselves

The *final* decision, sure. But if you look in the fediblock hashtag, it's an endless series of this playing out:

New-site admin: "I've just discovered chudbuds, who harassed my users!"

Experienced admin: "You should probably also check out this blocklist of similar sites!"

New admin: "Nope, I want to make my own judgments!"

New admin, hours later: "I've just discovered five more harassment sites, who took my earlier announcement as a confession I had an incomplete blocklist, and have been harassing my users!"

Experienced admins: "And that was preventable."

Who benefits from all the FUD around "don't trust other people's blocklists?" Hmm. Seems like mostly it's the worst-of-the-worst bad actors.

**Comment by Deuchnord** [comment]
> > Could you explain why you choose the "rage.love" blocklist as a source of truth, even for a tier 3 perspective ? The list is huge, seems kinda "random", and looking at https://rage.love/about#about-rage-love-en, the column "Reason" is empty for ALL the domains listed.
> 
> It's handy to have just because if I do have an issue with a site on this list, I know I can ask rage.love and see if it's an ongoing pattern or a one-off. That's kind of what a tier 3 perspective _is_, at least to me (I can't speak for oliphant).

Problem is, the purpose here of this repo is clearly not just to provide a way to check if an instance is known to be problematic, but to block it immediately. It would have been different if it would have been a tool that tells you the amount of known instances that have blocked/silenced it.

I can understand admins need tools to help them moderating what they receive from other instances. But *this* tool specifically sounds terrible.

**Comment by tyrosinase** [comment]
> I can understand admins need tools to help them moderating what they receive from other instances. But _this_ tool specifically sounds terrible.

Are you an admin, or are you basing this on what you *think* admins might do?

**Comment by Deuchnord** [comment]
I'm not an admin. Does it disqualify me to participate to this debate?

**Comment by tyrosinase** [comment]
No, it just changes what I assume your baseline knowledge to be.

Admins do not, contrary to what non-admins seem to think, just randomly grab blocklists off the internet and slap them on, *except* in the case of a brand-new site. (At least, good admins don't; there are some who are fairly capricious, but generally the blocklist is the least of the issues in that case.)

We have tools that show us whether a remote site has follow relationships with our users, and that affects whether we choose to silence, suspend, or just let it ride. The only reason somebody is using a Tier 3 or even 2 blocklist out-of-the-box is because they want to *set up* a site with the same flavor as an existing one: for instance when Artisan Chat spun off of Mastodon Art, it started out with the same blocklist. And that's fine, they're going to pitch it *to prospective users* as a selling point. Exactly who's being harmed by this?

Again, you've been pitched a lot of FUD about shared/crowdsourced blocklists, and you should probably question who benefits from pushing that agenda.

**Comment by u03c1** [comment]
> It's handy to have just because if I do have an issue with a site on this list, I know I can ask rage.love and see if it's an ongoing pattern or a one-off. That's kind of what a tier 3 perspective _is_, at least to me (I can't speak for oliphant).

I understand the ultimate goal, and separate in multiple tier is a valid way to let some choice to administrator. The question is why rage.love list have been choose as a tier 3 "Trusted source", even with a  warning that it's a "very restrictive blocklist" ? Based on what consideration ? 

"Trusted source" is not meaningless, so if it's just a random list populated by a solo admin who decide on his own to silence perfectly valid instance (like mamot.fr) unless it "may" receive a complain, and with no explanation, it should not be an option at all.

**Comment by tyrosinase** [comment]
A lot of admins trust rage.love's choices, and I am reliably told by (non-rage-love) French-speaking admins that mamot.fr has been kind of a cesspit, and while it's improving it's not unreasonable to still keep it silenced, if you're a site that doesn't federate with that sort of thing.

What you seem to be complaining about is the *existence* of tightly-moderated sites like rage.love and weirder.earth. There's demand for that, why do you complain about it? Do you feel like you have some entitlement to make them listen to you?

**Comment by 240-185** [comment]
> What you seem to be complaining about is the existence of tightly-moderated sites like rage.love and weirder.earth. 
No, the main gripe is _why_ these instances were chosen as the absolute reference regarding fediblocks.
You constantly dodge this question with constant red herrings and strawman arguments.

**Comment by tyrosinase** [comment]
There's a thing Github does where it puts a little tag next to the owners and contributors of a repo, and I really feel like they should also put one on people who *aren't* owners or contributors, because one doesn't necessarily notice its *absence*. So I'll point it out to you: I'm not dodging, I'm just not the owner of the repo so I can't answer it.

**Comment by tyrosinase** [comment]
(I can guess it's that, as I said, a lot of us trust rage.love's choices *for servers at that level* even if we don't choose to run our servers that way, and also that they were willing to permit their blocklist to be published in that way, which a lot of Tier 3 type servers are reluctant to.)

**Comment by sapphaos** [comment]
You could look into the source provided by the GitHub and have the answers as to why it was chosen. This is opt-in, this is why those instance were chosen, they chose to be there to share their blocklists. Nobody said rage.love has the best blocklist or whatever they just chose to share it.

> For starters, I curate a list of trusted sources, including my own server, pulled from the [Fedi Council](https://writer.oliphant.social/oliphant/the-fedi-council). Admins of Tier1+ servers have opted in to being one of the Trusted Sources, if you see them listed here, I have their explicit permission. 

https://writer.oliphant.social/oliphant/the-blocklist-algorithm
https://writer.oliphant.social/oliphant/the-fedi-council

Also yes, a lot of french instances have mamot at least silenced. I don't know why you're all acting so shocked when we told you we would do this so the moderation on the instance would start actually doing something.

**Comment by 240-185** [comment]
So we're back to square one: this instance relies on an algorithm and no manual reviews will be performed because the Fedi Council said so.

**Comment by tyrosinase** [comment]
Oh, so you're one of the FUD people. Noted.

**Comment by u03c1** [comment]
> A lot of admins trust rage.love's choices, and I am reliably told by (non-rage-love) French-speaking admins that mamot.fr has been kind of a cesspit, and while it's improving it's not unreasonable to still keep it silenced, if you're a site that doesn't federate with that sort of thing.

I can't debate this without numbers, and even if "a lot" is "100" or "1000", it will probably required more data to see if it's an objective reason that push to this action, if it was due to some specific account that can have been ban without excluding the instance, or something more biased. In all cases, a "reason" should be provided to understand what kind of policy dictate a domain to be muted. 

> What you seem to be complaining about is the _existence_ of tightly-moderated sites like rage.love and weirder.earth. There's demand for that, why do you complain about it? Do you feel like you have some entitlement to make them listen to you?

Not at all. And I even wonder what statement make you think such a thing.

Rage.love probably have their own reason to choose to block or unblock anyone they want, it's their decision, their rules. They can block the entire world, users may choose to stick or not. The question is why this project sgrigson/oliphant, decide to uses their list as a "trusted source". You seems to said "because we, as admins, trust them".  Ok, but in that case, a "Reason" in front each decision can be a good start to be qualified as "trusted" and "debated". You see, it seems that a lot of french users trust "mamot.fr", because it's owned by LQDN, a big french organisation about internet freedom. So I don't say that you are wrong by trusting them, but I say that we can't debate if we haven't qualified infos to understand the "why" on this choice. We need "history" to confront pov.

**Comment by ericdano** [comment]
Why do we need to manually vet a list when others, who have done prior vetting of these sites, and on whose views of the content of these sites we agree with?These lists are well documented as to what site is where and why they are there.As an instance runner, I don’t have the time to go through all 12k mastodon sites to individually look at them and go “yeah, they are all about hate speech there” or whatever. Someone else did that for me, documented it, and I will block it.Am I blindly just loading a list? No. I randomly looked at what I thought would be a good fit and am using that.The real reason these lists are a good idea and I find invaluable is in stopping a NEW site from spreading hate, etc on mastodon. If say a site pops up, and it’s just filled with a few users who are just going after people who are Trans on one site, I want to know about that. I want to proactively BLOCK that from my users. That is not what my instance is about.Sent from my iPadOn Jan 21, 2023, at 7:36 AM, 240-185 ***@***.***> wrote:﻿
So we're back to square one: this instance relies on an algorithm and no manual reviews will be performed because the Fedi Council said so.

**Comment by u03c1** [comment]
> These lists are well documented as to what site is where and why they are there.

I may have miss something, but all my answer are based on the fact that NO, it's not well documented. 
If I go to rage.love, all that I see is a list of muted server, with an empty "Reason" column. Can you pointed me to something better ?

**Comment by 240-185** [comment]
>Oh, so you're one of the FUD people. Noted.
I'm just interpreting @sapphaos's words.

>**Someone** else did that for me, documented it, and I will block it.Am I blindly just loading a list? **No**.
This is where I dissent. One claim is not enough, and references have to be crossed, preferably from multiple users from multiple instances. And when major instances are affected by a request of fediblock like mamot or piaille, I personally raise an eyebrow first.

**Comment by tyrosinase** [comment]
Yes, and if you RTM you will learn that this is a brand-new project and more sites are expected to be added.

**Comment by tyrosinase** [comment]
> but I say that we can't debate if we haven't qualified infos to understand the "why" on this choice. We need "history" to confront pov.

A reason-less listing just tells me, as admin, that the site has been flagged as perhaps needing closer attention. Which I paid: I went and checked French-speaking admins' opinions on the site, and learned, AS I SAID ABOVE, that they feel like mamot.fr used to be very bad and is struggling to improve. That's the system working as designed, what, exactly, is your problem?

**Comment by tyrosinase** [comment]
![rect31534](https://user-images.githubusercontent.com/9473609/213876143-97768be7-fa5d-4eb3-9238-253890ce4d32.png)

**Comment by u03c1** [comment]
> A reason-less listing just tells me, as admin, that the site has been flagged as perhaps needing closer attention. Which I paid: I went and checked French-speaking admins' opinions on the site, and learned, AS I SAID ABOVE, that they feel like mamot.fr used to be very bad and is struggling to improve. That's the system working as designed, what, exactly, is your problem?


The problem is that "Opinion" and "feel like" is not a reason. It's nothing. As you said, it's Reason-less. May be you trust each other, may be not, may be one of you is homophobic and you don't even know. And this person have the right to add a domain in rage.love list and "you trust him, period". But may be you do the thing right, you talk, you exchange proof, you don't bannished without further notice and so on... how can we trust a list, and choose to used this tier 3, if we have no way to understand the process ?

You see, this entire issue will not even exist if in front of the domain "mamot.fr', we can have an clear view of what lead to silenced the instance. Better, we can rely on this information to explain why to "not" move to this instance to users who would join the fediverse.

 So to be more specific, a reason is something like:
- "From 2 weeks since October 1st, multiple harassment for sexual orientation from multiple user of this instance were commited, see example here and here. Admin of the instance were noticed and didn't react. We put this domain on the XXX list. Admin were notified and can choose to prove us that the problem is solved to be whitelisted again."
 
The time spend by an admin for writing this "Reason" is even shorter that all the time we already spend on this github issue.

**Comment by sgrigson** [comment]
Duplicate issue to #2
