### ISSUE TITLE
shelter.moe

### ISSUE THREAD

**Issue by AxelTerizaki** [sgrigson/oliphant#8]
Hello.

I'm the admin of  the [shelter.moe instance](https://shelter.moe) and I find it strange that my instance is listed there, even more so in the "suspend" list.

Would it be possible to get off that list ?

I have no idea how it got there and why.

I have no idea how many people use these lists blindly. 

I have no idea how many will update their lists once and if the instance is removed from there.

Blocklists are certainly useful, until you find yourself on it for some reason because someone decided so.

Thanks in advance for your reply.

**Comment by AxelTerizaki** [comment]
I realize my first post might have been a little harsh but I've been trying to check several blocklists and appeal to the presence of my instance there, and I've already spent part of my evening doing that instead of something else, and this has gotten me a little annoyed. I apologize for that.

I also realize managing this kind of list can get you a lot of bad replies (I saw that other closed issue) but this alas comes with the power you have over small instances who got there by mistake or maybe because at some point someone had a bad experience with a user there and never sent a report and instead added the instance to a blocklist that then got aggregated into bigger ones.

And it's going to be a pain to check them all, I understand that. 

The fact that suc lists are decided by a handful of people is a little worrying.

Anyway, I just wanted to add that, sorry for the double notification.

**Comment by sgrigson** [comment]
The best answer I can give is that anyone who willingly federates with nazis and views it as everyone else's job to use personal blocklists rather than defederate from the *worst people possible* puts anyone who federates with them at risk.

Based on your server defederation policy (literally, lol, *none*) I'm sure you disagree with this assessment of mine. But it's my assessment people are looking for when they are setting up a server and wondering who is safe to federate with, and who is too much of a risk. They want a list of who might harbor bad actors, which servers will not be a safe home for them, as a new admin, which servers should I defederate?

I have to keep your server on the list, I'm afraid.

Whether you have a policy against hate speech or not, you willingly host the content from others who do on your server. You limit almost nothing, which means your users are subject to this toxicity, too. 

Perhaps your users even welcome such traffic? It seems a safe assumption. If your users had spoken up against it, you'd have defederated by now, especially if they'd threatened to leave over it. So we can safely assume there are users on your server who have no problem chatting with eveningzoo.club about racial IQs and sharing transphobic slurs with poa.st.

If you haven't needed to defederate from large portions of the fediverse already, the most likely assumption I'd make is that it's because you agree with their content. At the very least, it means *you have no problem with continuing to allow it.*

And that *does* tell me something.

We expect more than that, quite frankly. When we communicate with a server about an abusive user, we expect some common agreements, active moderation against hate speech being top of the list, but that includes protecting marginalized groups on your own server from racist, bigoted attacks against their identity.

There are servers out there that exist for little other reason than this.

You federate with them.

Some servers you federate with have harassed and targeted marginalized groups. These bad actors can find a safe haven because you do not defederate them, which normalizes their behavior. What others have rightfully kept out, you have let in.

Even if a server openly makes death threats against trans people *as a matter of policy* you federate with them.

You block *no* servers at all. Not even the outright pedo servers.

So...you federate with pedos, racists, transphobes, and fascists.

It makes you a risk that marginalized groups are not willing to take in federating with. Especially marginalized groups that don't like pedos, racists, transphobes, and fascists.

That's why you're on the list. Lax moderation, no real stand against any kind of hate speech because you have no standards of who you'll agree to communicate with, and an attitude of "just use a personal blocklist."

That attitude is fine on your own server, just not if you want to federate with us.

It didn't require anyone talking to the admin. We checked out your about page, saw what you considered acceptable, and thus considered you a risk not worth federating with.


If you haven't already, you should read about "The Paradox of Tolerance."

**Comment by Seirdy** [comment]
[My take on the issue](https://seirdy.one/notes/2022/12/06/fediverse-moderation/).

Even with auth-fetch enabled, instances with totally open federation are a risk since anything their users say about you will be pushed to bad actors.

Badness enumeration isn't an airtight solution but it significantly decreases moderation work and the probability of bad actors hurting our members.

**Comment by AxelTerizaki** [comment]
So if I TL;DR what you two said, if one isn't with you, they're against you. T

The only way to not be on these lists is to use it, or be either mastodon.social or mastodon.online since these are "allowed" even though they don't block who you think is bad. I can't say I get that logic... The rest can get defederated from instances following those blocklists.

No one endorses hate speech on shelter.moe. I mean, it's even in the rules. It's **explicitely** stated on the about page (sorry if it's in french but "Contenu haineux" is hate speech) So if anyone were to post such content (or other content that's not allowed) we'd suspend their account, obviously. I imagine a lot of instances do react that way with their rules.

I suppose nothing I'll say will change your mind, so let's keep it at that.

**Comment by fenarinarsa** [comment]
> Federation is a revocable privilege; instances that don't put in the work to use it responsibly have that privilege revoked.

If federation is a privilege, don't use blocklists and run an instance in whitelist mode. ¯\_(ツ)_/¯

Also the fact that the biggest fediverse instances are not in the list while they have similar rules than smaller instances that are silenced or suspended shows it's not a list built with strict rules in mind. As such, it's dangerous to use since you could have put an instance in the list just because you don't like it, or you don't like the admin, or a moderation rule that may have changed later, etc.

In any case using blocklists that you have no idea how they're made and maintained is a bad moderation practice anyway. There's a reason why the biggest instances don't use such lists :)

That said it's up to the admins anyway.

**Comment by LouisNitag** [comment]
Hmm, I see your point, but TBH why don't you block AWS/GCP/Azure hosted instances? Those public cloud providers host nazi-runned instances, so they are not against it. And if I follow you logic you should block those actors not blocking nazis.

**Comment by sgrigson** [comment]
*If federation is a privilege, don't use blocklists and run an instance in whitelist mode.*

Or we maintain blocklists and trust the larger fediverse. Guess which option we chose?

*So if I TL;DR what you two said, if one isn't with you, they're against you.*

No, that's not at all what I said. It's very easy to not get defederated.

You just have to make an effort.

To everyone else in this thread:

[Don't Trust Me Or My Blocklist](https://writer.oliphant.social/oliphant/dont-trust-me-or-my-blocklist)

**Comment by aeris** [comment]
> In the case of a mono-user instance you probably won't receive toots from bad instances and so you don't need to block them. You don't even know they exist. And so with your method those kind of instances will fall in your blocklist…

I'm in this case. My single-user instance is currently blacklisted for no reason, and I never face a single nazi or similar content. The most bad behavior content I never faced was currently from… admin of "strongly moderated" instance denying me my non-binary ace pansexual flag… (still reported as anti-LGBT content since 2 years and never moderated since) :shrug: 

And currently, because those blocklists include mono-user instance domain and so processing personal identifiable information, it just violate many many GDPR rules and are per se… unlawfull…
Private message sent to @sgrigson to address this issue, will see what happen on that topic too, but I'm curently expecting the same as Mastodon core dev team on this topic : "ahahaha, GDPR… what about NOPE?".

**Comment by tyrosinase** [comment]
> No one endorses hate speech on shelter.moe. I mean, it's even in the rules. It's **explicitely** stated on the about page (sorry if it's in french but "Contenu haineux" is hate speech) So if anyone were to post such content (or other content that's not allowed) we'd suspend their account, obviously. I imagine a lot of instances do react that way with their rules.

I don't think you've fully considered the way federation works: https://wirebird.com/artiblocks/defining-secondhand-smoke

**Comment by tyrosinase** [comment]
If you want to go to the absurd extreme, sure.

But counterpoint: turns out the `foulspeech` crowd is pretty much a self-contained cyst on the internet, and you can very easily choose which fediverse you want to be part of by simply defederating from a fairly well-defined list. You can choose not to decide, but you kinda can't whine about getting lumped in with the edgelords if you insist on staying part of the edgelord b ubble.

**Comment by tyrosinase** [comment]
Clarification: I'm not affiliated with this repo, though my instance's public blocklist feeds into various bits of oliphant's work.

You're blocked on mine, shelter-moe isn't but probably will be whenever I get around to it. Cope.

**Comment by aeris** [comment]
Yeah, and just a question so : why i'm blocked on your instance? I bet it's only **personal decision** motivated by just nothing else than individual disagreement (I have strictly nothing against that at all) but this would definitively not be propagated on other server without disclaimer about that fact and can be state as "protecting federation from them".
I'm not blocked because of my behavior, content or opinion (or come with evidence, nobody was ever able to provide one) but only because of personal disagreement around totally acceptable (as not infringing your CoC or social rules) position not shared between us.

**Comment by tyrosinase** [comment]
And yet you *are* blocked because of your behavior and content, as is quite explicitly stated in my block reason. Stop whining and deal with there being consequences to your own actions.

**Comment by aeris** [comment]
Nobody was ever able to come with evidence of bad content or opinion from me. Never ever.

**Comment by tyrosinase** [comment]
And yet.

**Comment by aeris** [comment]
That's not a bad behavior forbidden by your CoC even the most hard one.
It's not a `foulspeech` "debating" with a `fairspeech` (with one not acceptable opinion and one acceptable) but 2 `fairspeech` debating about 2 acceptable social decisions but not compatible.
I don't endorse nazi, I block them when I see such content, I report them to cops, I defend LGBT, black, disabled people, respect any choosen flags… Not a single opinion or speech from me can be stated against a single CoC here.
Only my personal "technical" opinion about Mastodon federation, no interference from external instance,  no hardcoded blocklist inside Mastodon clients or other totally acceptable cause my block.
At the opposite, the exact same people asking for my block refuse to acknoledge my LBTQ flag and proceed with exact content or opinion forbidden by your CoC and currently are **NOT** moderated or excluded from federation. I keep proof of that since couples of years and contrary to you, I can proof my words.

**Comment by tyrosinase** [comment]
More words doesn't make your argument any more true, it just makes you sound whinier.

**Comment by aeris** [comment]
And less word not make your words true too.

**Comment by aeris** [comment]
Not verifiable.

**Comment by aeris** [comment]
And this discussion is exactly the point about the trouble of such blacklist.
Some people on blacklist are just here for unknown/not justified or verifiable (and worse fairly) reason, nobody can explain or justify why and block seems more personal disagreement/grievance, the same people blocking them are accused of real bad behavior but no action taken.
It's just pure discriminating censorship for some instances.

**Comment by tyrosinase** [comment]
🍷🍷🍷

**Comment by Dehelssey** [comment]
See, @aeris i wasn't even blocking you at a personnal level because, yes, you don't really cross the line. 

Like, you're not frontally rude, just VERY verbose. Kinda spammy tho... and quickly escalating into a neverending thread of posts...

Just like here. No insults, nothing strictly **forbidden**, no hate speech or else... you're just being as unpleasant as you can get without being mean. A lot of whining also. 

So yeah, technically you might have never did anything wrong. (Even tho you really seem likecyou never question yourself)... But, god, you like running your mouth, and stating A LOT of "facts" no one has the time or ability to check. 

You drown us under tons of words and posts and when we answer you on A you dismiss it and talk about B and so on and so on... 

You basically are the incarnation of [Gish Gallop](https://en.m.wikipedia.org/wiki/Gish_gallop) and your annoying attitude is what's getting you blocked by more and more people.

Once you'll get it...

**Comment by aeris** [comment]
Don't invert role. Why i "gish gallop" ? Because every time it's the same shit and **you** start gish galloping.
This issue is exactly on point.
@AxelTerizaki just come asking "oh, why i'm on this list, i don't understand" (and then excuse himself to be a little rude) with a good spirit/mind open to discussion and the next post is a litany of gibberish litteraly **a screen long** post insta-locking any conversation…

**Comment by Dehelssey** [comment]
So, no, blocklists are not **perfect**

But they're better than nothing to keep a good neighborhood on the fedi

And yes, mastodon.social and .online might deserved to be blocked. A lot of instances silence them at least.

Also, yes, solo instances don't always **require** blocks to keep bad actors out of their federation... at least at first

But then again, blocklists are an efficient solution. You can't deny it's easier to block dozens (even hundreds?) of bad actors than whitelist thousands of good ones...

Either you're willing to show good faith and block those infamous instances so you're not associated with them...

Or you'd rather, for whatever political/philosophical reason, keep every gate open and then you shouldn't give a damn about being blocked by some "extremists", should you ?

**Comment by Dehelssey** [comment]
> Don't invert role. Why i "gish gallop" ? Because every time it's the same shit and **you** start gish galloping. 

Wow. Says the guy who's actually inverting roles. When did i gish galloped ? Not here that's for sure. Nor on any of the dozens of pro nuke thread you offered me and some other people. Feel free to share any of them, the numbers will speak for themselves, pretty sure there is like 5 posts feom you for each from me^^

Anyway, you missed the "question yourself" part. Guess we're stuck once again.

**Comment by aeris** [comment]
("you" as people here, not "you" as a single person)

**Comment by Dehelssey** [comment]
BTW i've already told @AxelTerizaki my opinion back on the fedi. We don't really see the things the same way but at leasy **he** didn't post **nine** posts in someone else's thread to complain.

Pretty sure he can question himself

**Comment by Dehelssey** [comment]
> ("you" as people here, not "you" as a single person)

How convenient.

Anyway still doesn't work. You asked for reasons. They were given. You refused them. How is that "us here" gish galloping ?

**Comment by aeris** [comment]
> he didn't post nine posts in someone else's thread to complain.

For your information, Mastodon is a **federated** **social network**.
So even if this post is started from one people, it doesn't mean this person is alone.
This topic is currently discussed on Mastodon.

**Comment by Dehelssey** [comment]
> I can also return the "question yourself" when "your" side currently:
> 
> * not moderate or evict people refusing self LGBT determination
> * not blacklist instance tolerating the previous people
> * proceed with defaming position from self-generated context
> * confess hunting people to harass them for free
> * conduct bullying partner of people previously targeted


For the record i'm not using that blocklist nor am i contributing to it so... 

Anyway, just like you i'd like some evidence before taking actions... 

Right now you stated things you present like facts. People i trust have a different version of the story. Previous encounters i had with you don't encourage me to trust you that much... 

I'm not saying i'm right, just that given the situation, i can only rely on what you say and what they say and chose to pick a side or not.

**Comment by Dehelssey** [comment]
> > he didn't post nine posts in someone else's thread to complain.
> 
> For your information, Mastodon is a **federated** **social network**. So even if this post is started from one people, it doesn't mean this person is alone. This topic is currently discussed on Mastodon.

Ooooh tha'k you for explaining me how the fediverse works. (That was sarcasm) 
For you information GitHub is **not** a federated social network so yeah you kinda hijacked an issue about a specific instance to complai' about... **you**

(God why do i keep answering you)

**Comment by aeris** [comment]
Sorry, but it's many more "facts" than "like facts".

- Litterally a people from your side refusing to people non-binary, ace, panromantic, disabled or other marginalized flags. There is **NEVER EVER** a situation where such comments could be tolerated. No condition. Even for "philosophical" or "social" purpose as stated on some of such creepy assertions.

- Previous toot was signaled to instances which **NOT** taking action about this content since 2019

- A people proposed to people to add speaking flag into bio to help identifying language then called people xenophobic & racist when seeing such a flag on bio. Content signaled too, no moderation action since 2019 too. Very efficient way to add more "bad guy" flag on a people unable to defend himself ("he says he is a good ppl, but see, xenophobic flag on their bio", omitting "flag I propose to them to add").  

- Litterally a people confessing "Too bad I wanted a free opportunity to beat him up" when he discovered homophobic speaking were not really said by a person he wants to clash for no reason

- Litterally people now suffering from PTSD and agoraphobia because such "good people" just bullying them for the only reason to be the partner/relationship/friend of a flagged "bad people", and "good people" publicly pretending very falsy & cringe things (manipulation, physical threats…) too

At the opposite, nobody here can even proof a single bad behavior from flagged "bad people" (i'm not alone in this category).

**Comment by aeris** [comment]
> But then again, blocklists are an efficient solution. You can't deny it's easier to block dozens (even hundreds?) of bad actors than whitelist thousands of good ones...

No, it's not very efficient. It's even so uneffective than pretty many people now requesting for blocklist have a long story and fight against blocklist when coming from other people before that.
And it's only effective for "obviously illegal" content, but can be very dangerous too for other content. And worse when such blocklist is uncontrolled and shared. And sooooooooo much dangerous when refusing to apply them blindly just put yourself on this blocklist.
Once again, I never challenge the fact that nazi/pedo/illegal instances was blocked but only the fact blocklist currently disgress from that purpose to something containing non neutral, randomly justified if not even personal block. And worse than challenging such block is just considered as the same as promoting illegal content.

> Either you're willing to show good faith and block those infamous instances so you're not associated with them...

If you have that much need to "show good faith to be not associated to them", I definitively will start by introspecting yourself. I haven't the need to block them to dissociate myself completely from them. And as stated above, I vastly never ever meet such content on my instance (I vaguely remember 1 or 2 such toots in more than a decade on fediverse).
And from a legal point of view, European law explicitly state than the only way to **not** endorse a content is to **not** block at all (article 12, European directive 2000/31/CE 08/06/2000).

> Or you'd rather, for whatever political/philosophical reason, keep every gate open and then you shouldn't give a damn about being blocked by some "extremists", should you ?

For political reason, it's not endorsing nazi position, but just democratic safeguard we fight for since decades. We always refused to politics or governments the right to discretionary blocking measures (remember the "red hand" block page for terrorism in France) and worse the "trust me it's bad, and if you challenge that you are on the bad side".
There is no difference between what we (and I guess/hope this "we" include yourself too) refuse in 2000-2015 to our governments, in national, European or international laws and what you ask now once you become the government.
Purposes don't change since 2000 and bad ideas from this time are still bad ideas in 2023.

**Comment by sgrigson** [comment]
I have ignored this absolute hellthread with good reason. If you were really hoping I heard whatever ^^^ *that* was, please rest assured, I did not. 

Closing thoughts:

1. The oliphant.social list shows servers I don't federate with, or silence. There are other lists from servers I trust, showing who they federate with or who they silence. There is *no commentary* attached to the lists here on github. The 'public_reason' for import is blank. No one is being called out by name as anything except as a server we don't federate with, or a server we silence.
1. I provide access to publicly-available information as a public service, as a hobby. Not for commercial use. It is a *necessary* part of the regular operation and maintenance of a social media server when it comes to warding off bad actors and curating a healthy space for communities online.
1. You're not going to successfully argue me into "blocks don't work." They absolutely do. We disagree. Move on.
1. Btw, threatening people with fake legal action is exactly the kind of harassment I'd want other people to avoid.

Thread closed.
